sudo: required
services:
  - docker

before_install:
  - docker build -t hcengiz98/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run hcengiz98/react-test npm test -- --coverage

after_success:
  - docker build -t hcengiz98/multi-client ./client
  - docker build -t hcengiz98/multi-nginx ./nginx
  - docker build -t hcengiz98/multi-server ./server
  - docker build -t hcengiz98/multi-worker ./worker
  #Log in to the docker CLI
  - echo  "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push hcengiz98/multi-client
  - docker push hcengiz98/multi-nginx
  - docker push hcengiz98/multi-server
  - docker push hcengiz98/multi-worker
  